# Generated by Django 4.2.4 on 2023-12-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumeshortlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="Sample",
        ),
    ]
