# Generated by Django 4.2.4 on 2023-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeshortlist", "0003_user_delete_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="resumes",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=75)),
                ("dob", models.CharField(max_length=75)),
                ("sex", models.CharField(max_length=75)),
                ("email", models.CharField(max_length=75)),
                ("contactno", models.CharField(max_length=75)),
                ("username", models.CharField(max_length=75)),
                ("password", models.CharField(max_length=75)),
                ("address", models.CharField(max_length=75)),
                ("selected", models.IntegerField(default=2)),
            ],
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
